Repository netlify/netlify-commons, pull requests merged in 2020-10, with the labels that each got.

#182 chore(ci): improve Docker Compose files for a more robust experience running integration tests
  Dockercompose.test.yml
  Dockerfile.setup
  kafka/consume.go
  kafka/consume_test.go
  kafka/integration_test.go
Labels: type: chore

#186 docs(kafka): update README
  kafka/README.md
Labels: type: chore

#188 Add backend as codeowner
  .github/CODEOWNERS
Labels: type: chore

#187 Add method to get all enabled feature flags for a user
  featureflag/config.go
  featureflag/featureflag.go
  featureflag/featureflag_test.go
  featureflag/fixtures/flags.yml
  featureflag/mock.go
  go.mod
  go.sum
Labels: type: feature

#190 Make featureflag.MockClient return enabled flags in AllEnabledFlags
  featureflag/mock.go
Labels: type: bug

#191 fix(kafkatest): add missing fake consumer methods
  kafka/kafkatest/utils.go
Labels: type: chore

#192 feat(kafka): add ConsumerFactory in order to align future developments
  kafka/consume.go
  kafka/consume_test.go
  kafka/kafkatest/utils.go
Labels: enhancement, type: chore

#193 feat(kafka): add test for FakeKafkaProducer WaitForKey
  kafka/kafkatest/utils_test.go
Labels: type: feature
