Repository netlify/netlify-commons, pull requests merged in 2020-09, with the labels that each got.

#166 user traffic log line parser
  parser/user_traffic.go
  parser/user_traffic_test.go
Labels: type: chore

#161 Adding produce and consume from partition capabilities to kafka lib
  Dockercompose.test.yml
  Dockerfile.setup
  Dockerfile.test
  Makefile
  go.mod
  go.sum
  kafka/config.go
  kafka/consume.go
  kafka/consume_test.go
  kafka/hash.go
  kafka/hash_test.go
  kafka/integration_test.go
  kafka/produce.go
  kafka/utils.go
Labels: type: feature

#169 make the recoverer tie back to a request
  router/middleware.go
  router/middleware_test.go
  tracing/context.go
Labels: type: chore

#170 handle errors better in the tracing and spans
  router/errors.go
  router/errors_test.go
  router/middleware.go
  router/middleware_test.go
  tracing/req_tracer.go
Labels: type: chore

#173 Add traffic-mesh signature decoder.
  go.mod
  go.sum
  trafficmesh/signature.go
  trafficmesh/signature_test.go
Labels: type: feature

#179 Expose LD users to enable custom attributes.
  featureflag/featureflag.go
  featureflag/mock.go
  go.sum
Labels: type: chore

#180 fix(kafkaclient): do not close logs channel
  kafka/config.go
  kafka/integration_test.go
Labels: type: bug

#178 feat(kafka): add detached consumer
  kafka/consume.go
Labels: type: feature

#181 Return dummy featureflag client on error
  featureflag/featureflag.go
Labels: type: chore

#185 Proactively trim dangling comma's from AID values
  parser/user_traffic.go
  parser/user_traffic_test.go
Labels: type: bug
