Repository netlify/netlify-commons, pull requests merged in 2020-05, with the labels that each got.

#119 Keep up with the latest
  .travis.yml
Labels: type: chore

#121 code owners, code of conduct, license
  .github/CODEOWNERS
  CODE_OF_CONDUCT.md
  LICENSE
Labels: type: chore

#122 Fix panic in ntoml when checking paths
  ntoml/netlify_toml.go
Labels: type: bug

#123 Fix err check in ntoml path checker
  ntoml/netlify_toml.go
  ntoml/netlify_toml_test.go
Labels: type: bug

#126 Add plugin package names to netlify.toml
  ntoml/netlify_toml.go
Labels: type: feature

#127 Don't nest plugins config under build in netlify.toml parser
  ntoml/netlify_toml.go
Labels: type: feature

#130 fix: add fossa config
  .github/workflows/fossa.yml
Labels: type: bug
