Repository netlify/netlify-commons, pull requests merged in 2021-04, with the labels that each got.

#228 fix: update mongo driver
  go.mod
  go.sum
Labels: type: chore

#231 chore: add initial stalebot config
  .github/workflows/stalebot.yml
Labels: type: bot

#232 Update stalebot.yml
  .github/workflows/stalebot.yml
Labels: type: chore

#233 feat: add field for pinned plugin version
  ntoml/netlify_toml.go
Labels: type: feature
