Repository netlify/netlify-commons, pull requests merged in 2021-11, with the labels that each got.

#260 Must read value with atomic
  metriks/gauge.go
Labels: type: bug

#261 Add service tag to metrics and traces
  metriks/metriks.go
  metriks/metriks_test.go
  tracing/config.go
Labels: type: feature

#264 feature: allow specifying custom featureflag atributes
  featureflag/config.go
  featureflag/featureflag.go
  featureflag/global.go
  featureflag/mock.go
Labels: type: feature

#263 fix: panic on server shutdown from closing closed channel
  server/server.go
Labels: type: chore

#267 fix: properly handle urls in saferoundtripper
  http/http.go
  http/http_test.go
Labels: type: bug

#268 Have fakeConsumer.close take the lock before closing the msg chan
  kafka/kafkatest/utils.go
Labels: type: chore
