Repository netlify/netlify-commons, pull requests merged in 2022-01, with the labels that each got.

#279 Mongo go driver 1.8.1
  go.mod
  go.sum
Labels: type: chore

#278 BREAKING CHANGE: Remove kakfa package and tests
  Dockercompose.test.yml
  Dockerfile.setup
  Dockerfile.test
  Makefile
  README.md
  go.mod
  go.sum
  kafka/README.md
  kafka/config.go
  kafka/consume.go
  kafka/consume_test.go
  kafka/doc.go
  kafka/example_test.go
  kafka/hash.go
  kafka/hash_test.go
  kafka/integration_test.go
  kafka/kafkatest/utils.go
  kafka/kafkatest/utils_test.go
  kafka/produce.go
  kafka/produce_test.go
  kafka/utils.go
  kafka/utils_test.go
Labels: type: chore

#289 chore: Test on Go 1.17
  .github/workflows/build.yml
Labels: type: chore

#288 chore: Configure bots to make managing this repo easier
  .github/dependabot.yml
  .github/renovate.json
  .github/workflows/pr-conventions.yml
  .github/workflows/release-please.yml
Labels: type: chore

#285 Update fossa to point to main
  .github/workflows/fossa.yml
Labels: type: chore

#291 chore: Fix renovate schedule setting
  .github/renovate.json
Labels: type: chore

#295 chore: Setup kodiak
  .github/.kodiak.toml
Labels: type: chore

#301 chore: Improve release please details
  .github/workflows/release-please.yml
Labels: type: chore, automerge

#304 chore: Aquire token for release please on the fly
  .github/workflows/release-please.yml
Labels: type: chore, automerge

#305 chore: add env to api info
  server/server.go
  server/server_test.go
Labels: type: chore

#313 chore: update how we get request IDs
  router/router_test.go
  tracing/context.go
  tracing/logging.go
  tracing/req_tracer.go
Labels: type: chore

#321 feat: added serializable http.Header type
  util/headers.go
  util/headers_test.go
Labels: type: feature
