Repository netlify/netlify-commons, pull requests merged in 2022-06, with the labels that each got.

#336 chore: remove the parser package to its own repo
  parser/user_traffic.go
  parser/user_traffic_test.go
Labels: type: chore

#338 feat: make Router.enableTracing configurable
  server/server.go
Labels: type: feature

#339 chore: add note about release-please
  .github/pull_request_template.md
Labels: type: chore

#341 docs: CODEOWNERS update 202206
  .github/CODEOWNERS
Labels: type: chore

#342 fix: prevent race condition in Stop method on gauge
  metriks/gauge.go
  metriks/gauge_test.go
Labels: type: bug
